# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstaClone', '0003_commentmodel_likemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='tag',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='caption',
            field=models.CharField(max_length=250),
        ),
    ]
